### ISSUE TITLE
Correct Way to Offset a 3rd shift job with circadian lighting. (offset 9 hours, OR sunrise at 3pm)

### ISSUE THREAD

**Issue by VarenDerpsAround** [claytonjn/hass-circadian_lighting#74]
I cannot for the life of me figure out what I am doing wrong here. I have read the docs as far as setting an offset for the lighting, but it does some real funky stuff when I do it. I've tried (to no avial) offset for both sunrise and sunset of 09:00:00, -09:00:00, of +4...ect ect. None of them seems to fully cycle though the day night cycle. I will show you some of my frustrations. I tried uninstalling/reinstalling it fully even after commenting out the sensors/config. 

I suppose the general question is, what is the correct way to set an offset of a third shift job where we want the sunset to be 3am, and the sunrise to be 3pm. Understandably, you should just be able to set the sunrise_time: 15:00:00 and sunset_time: 03:00:00 but it seems to be doing some weird fluctuation when reaching it's high point, and I'm not sure what I'm doing wrong. 

Do I need to set both sunset_time and sunrise_time? or is setting both of them screwing something up? 

Love Love Love this integration btw, we have used it for 3 months now, and now that we are switching to 3rd shift, this would super duper come in handy. The photo is what the sensor/graph shows when I set a 9 hour offset.
![image](https://user-images.githubusercontent.com/58420778/75994728-055e8100-5ec1-11ea-8dee-26300f626df1.png)

**Comment by VarenDerpsAround** [comment]
I may have found a workaround. Although, I'd like to use the offset or settime functions instead of this solution.

But I calculated that 12 hours behind/ahead of my time, and almost latitudinally, Bangkok, China is perfect. So, I plugged in the lat, and long of the location desired and it seems to be working thus far as I needed.  Cheers.

**Comment by claytonjn** [comment]
> I will start off with everything I have tried.
> 
> I have tried several versions of "sunset_time" +- "sunrise_time" as well as "sunset_offset" +- "sunrise_offset"
> 
> I also now also tried to plug in a latitude and longitude of a location on the opposite side of the earth then I am. This should work, however it seems to break around 6pm at night and fails to start. I'll also say it was working with this, and only this solution today until 6pm.
> 
> I'm out of ideas. If anyone if still listening to this thread, seeing as it was just updated a couple days ago, I had a couple of questions and hopefully we can find a solution that works!
> 
> First question, it seems that the "float" for latitude and longitude is -90-90 as stated in your readme. This isn't ... right? longitude goes longer then 90 degrees. for instance, Bangkok, Central Thailand shows a longitude of 100.523186 ? Wondering if this is the problem?
> 
> Thoughts?

**Comment by claytonjn** [comment]
> I am now confident the issue with my final solution lies in the -90-90 longitude restriction. Please update accordingly. Upon clearing the long-lat the add-on starts up. Upon adding the lat it starts up, once I add the long over 90.00+, the add-on fails to initialize.

**Comment by claytonjn** [comment]
The latitude and longitude restrictions come from Home Assistant helpers, nothing I've coded. The WiKi was in error, the longitude range is actually -180 - 180 as it should be. What errors are you seeing when it fails to initialize? If you tell me exactly what long/lat you're trying I can look into it more closely, it's likely an arithmetic issue.

**Comment by VarenDerpsAround** [comment]
13°44'N / 100°30'E is Bangkok, Thailand, which is exactly 12 hours difference. The error only occurs when it ticks past a certain point in the day, and persists until a certain point in the morning. I'm in the spot where it works, but come 6pm tonight it will completely break. 

I have tried doing the offset of 8-12 hours, I will try that now and try to give you a picture of what it's doing. essentially it will rise up to it's highest point in the lighting, then fall in seconds to it's lowest point, rinse repeat.  I'd love to it to be pretty much the same as regular circadian lighting, except 8-12 hours difference. The only reason I'm pushing it the full 12, is that the longitude, and latitude for 12 hours away was working, during the day. 

Maybe we should just start with what would work instead of figuring out why what I'm doing doesn't. I've tried alot of different options within the configuration.  I've never been able to get the circadian lighting to work the way it does normally with offset.

**Comment by claytonjn** [comment]
> Again, if I could just have an example of what should work and we start from there that would be most excellent.

Setting an offset or setting lat/long exactly like you're doing _should_ work. Or just setting `sunrise_time` and `sunset_time` - have you tried that?

I don't know what's causing the issue with setting lat/long but when I get a chance I will set the same values you tried and look closely at what's going on. The offsets should also work but I have a feeling that something's getting screwed up with days. Dates and times can be tricky to work with; if the next sunset is today at 7PM and you want to offset it by 8 hours you're now saying that sunset is at 3AM **tomorrow**. To do all the calculations I have to use logic to figure out where "right now" fits in between sunrise and sunset, so when days change it complicates everything significantly - I'm guessing that's where the issue is.

**Comment by VarenDerpsAround** [comment]
Alright, I see. So, consider that sunrise and sunset are roughly 12 hours apart, how do we offset it 8 hours without breaching the midnight barrier? What you're saying sounds like the likely cause, and I stated it only breaks certain times of day when it's correctly set to the latitude and longitude of Bangkok. So, the sunrise sunset barrier is crossed causing the syntax error. Good catch!

**Comment by claytonjn** [comment]
I just have to look through the logic that determines whether the sun is considered above or below the horizon (based on all offsets or hard-coded values) and determines what percentage above or below the horizon the sun should be considered. 

The tricky part is that because not all HA instances are installed the same, I believe it's possible that in some instances Python may be defaulting to the local timezone of the host whereas some instances it may be defaulting to UTC, etc. 

I need to take a step back and think through all the different possible scenarios. I believe they are:
- Nothing configured
-- Timezone at HA configured lat/long/elev
- One or more offset configured
-- Timezone at HA configured lat/long/elev
- One or more time configured
-- Timezone at HA configured lat/long/elev
- One or more latitude, longitude, or elevation configured
-- Timezone at CL configured option (combined with HA configured lat/long/elev if all three are not set)

Once I use the above guidelines to determine what the timezone should be I think I then need to explicitly set the timezone for all datetime objects so that the logic to determine if sun should be considered up/down works properly.

That's all assuming the issue is what I'm thinking it is.

**Comment by VarenDerpsAround** [comment]
Now that it is past sunset, are there any troubleshooting steps I can take on my end to help you?

**Comment by claytonjn** [comment]
Turning on debug logging may help explain the behavior you're seeing. It should long what values are being used for sunrise and sunset and some more useful information.

**Comment by VarenDerpsAround** [comment]
I don't see how to turn on debugging in the configuration wiki.

**Comment by claytonjn** [comment]
https://github.com/claytonjn/hass-circadian_lighting/wiki/Debugging

**Comment by VarenDerpsAround** [comment]
So, I have let it run for a while, this is what I've come up with. 
This is an error I am getting in the logs, note the time.
```Logger: homeassistant.util.logging
First occured: 9:35:22 AM (1 occurences)
Last logged: 9:35:22 AM

Exception in update_switch when dispatching 'circadian_lighting_update': ()
Traceback (most recent call last):
  File "/config/custom_components/circadian_lighting/switch.py", line 253, in update_switch
    self._hs_color = self.calc_hs()
  File "/config/custom_components/circadian_lighting/switch.py", line 236, in calc_hs
    return color_xy_to_hs(*self.calc_xy())
  File "/config/custom_components/circadian_lighting/switch.py", line 233, in calc_xy
    return color_RGB_to_xy(*self.calc_rgb())
  File "/config/custom_components/circadian_lighting/switch.py", line 226, in calc_rgb
    if self.is_sleep():
  File "/config/custom_components/circadian_lighting/switch.py", line 216, in is_sleep
    return self._sleep_entity is not None and self.hass.states.get(self._sleep_entity).state == self._sleep_state
AttributeError: 'NoneType' object has no attribute 'state'
```
![image](https://user-images.githubusercontent.com/58420778/76630658-6532d880-650e-11ea-957b-4ed33edbe0a4.png)

I don't think the coordinates are correct as it looks like the rhythm isn't quite right. I'll update the coords back to what worked before and record the errors when they pop up.

**Comment by VarenDerpsAround** [comment]
BAH! I figured out why I was having the error. I changed the name of my sleep switch for easier use with alexa, well my dumb brain forgot about the input boolean for the sleep switch.

I updated the code throughout and am rebooting now. I have debugging enabled, so tonight and throughout the coming hours I will check for errors, and see how it's handling the latitude and longitude. 

My code are as follows, thanks again for the help with this. Maybe we have already fixed it just by going though all the different configurations, but then again, I won't know until it does a full/half cycle of the lighting.

```
    circadian_sleep_lighting:
        name: Circadian Lighting Sleep Switch
        initial: off
```
```
circadian_lighting:
    min_colortemp: 4000
    max_colortemp: 7800
    latitude: "13.736717"
    longitude: "100.523186"
```

```
    - platform: circadian_lighting
      min_brightness: 15
      max_brightness: 100
      sleep_entity: "input_boolean.circadian_sleep_lighting"
      sleep_state: "on"
      sleep_colortemp: 1000
      sleep_brightness: 10
      lights_rgb: 
        - light.bench
        - light.laundry
        - light.litter
        - light.overhead
        - light.zed
        - light.front_doorway
      lights_brightness:
        - light.dining1
        - light.dining2
        - light.kitchen_2
        - light.pantry_2
        - light.upstairs_stairway
        - light.bed_one
        - light.bed_two
```
```

**Comment by VarenDerpsAround** [comment]
It worked all day until I rebooted. Got This and this
![image](https://user-images.githubusercontent.com/58420778/76693869-feaad900-6639-11ea-97a6-ab468f0aa5be.png)
![image](https://user-images.githubusercontent.com/58420778/76693878-12563f80-663a-11ea-8e23-8f89a7386d66.png)

**Comment by claytonjn** [comment]
'y' gets set if it's after sunrise and before sunset or if it's after sunset and before sunrise. For that to happen it would have to be after sunrise and after sunset or before sunrise and before sunset. To troubleshoot I would need to see the debug lines that were logged before that error which would show what was being used for `now_seconds`, `sunrise_seconds`, and `sunset_seconds`.

**Comment by VarenDerpsAround** [comment]
Alright, I let it run for a some time without rebooting it, it's been disabled the whole time, the error persists after the 6pm mark until the 6am mark if and only if I reboot during that time.

Here is my logger....

And now is the part where I tell you I can't find my circadian lighting log (the output from the debug config you gave me)

Is it possible it is gone since the circadian lighting component is not loaded?

Well, in this case, I'm once again rebooting and seeing what I can find, letting it run till 6pm, then checking for a log? Maybe I am being daft but I do not understand what I'm supposed to find. How can I find this?

```To troubleshoot I would need to see the debug lines that were logged before that error which would show what was being used for now_seconds, sunrise_seconds, and sunset_seconds.

**Comment by claytonjn** [comment]
> And now is the part where I tell you I can't find my circadian lighting log (the output from the debug config you gave me)

Where are you looking? Everything is logged to the home-assistant.log file in your config directory. You can also see it on the /developer-tools/logs page but you'll have to click the "LOAD FULL HOME ASSISTANT LOG" button because the top part only displays errors and warnings.

**Comment by VarenDerpsAround** [comment]
That is the error I am getting in that log though, I don't see any other circadian lighting errors, I'll control f quick and paste all instances of circadian lighting in the log

```
2020-03-14 21:06:36 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for circadian_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```


```
2020-03-14 21:17:39 ERROR (MainThread) [homeassistant.setup] Error during setup of component circadian_lighting
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/circadian_lighting/__init__.py", line 112, in setup
    interval, transition)
  File "/config/custom_components/circadian_lighting/__init__.py", line 138, in __init__
    self.data['percent'] = self.calc_percent()
File "/config/custom_components/circadian_lighting/__init__.py", line 267, in calc_percent
    a = (y-k)/(h-x)**2
UnboundLocalError: local variable 'y' referenced before assignment
2020-03-14 21:17:44 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform circadian_lighting.switch: Unable to set up component.
```
```
2020-03-14 21:17:47 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform circadian_lighting.sensor: Unable to set up component.
```

This is every error for circadian lighting. Hope this helps!

**Comment by claytonjn** [comment]
You should definitely see some debug stuff after the warning and before those errors. Are you sure that you put all three lines under `logger` and have them set to debug? 

I just tested with your config and it's not causing problems for me right now but that's probably because our local timezones are different.

**Comment by VarenDerpsAround** [comment]
Okay, now I have this sorted, at least until it breaks tonight and I can get the logs sorted.

For whatever reason, kinda bothers me but my logs.yaml file... vanished? I'm not sure, I don't remember restoring from a snapshot, idk. but my logs.yaml file are as follows
``
logger: !include yamls/logs.yaml
``
in the yamls folder is logs.yaml which contains
`` 
 logs:
    custom_components.circadian_lighting: debug
    custom_components.circadian_lighting.sensor: debug
    custom_components.circadian_lighting.switch: debug
``
also, I can tell today is gonna be one of THOSE days when my copy paste breaks mid way through this post...lol. Windows, please! I will update this issue thread tonight with those logs, hopefully, rather definitely this time. thank you for your patience.

**Comment by VarenDerpsAround** [comment]
Is this it?

```
Logger: homeassistant.core
First occured: March 16, 2020, 7:08:01 PM (1 occurences)
Last logged: March 16, 2020, 7:08:01 PM

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/circadian_lighting/__init__.py", line 305, in _update
    self.data['percent'] = self.calc_percent()
  File "/config/custom_components/circadian_lighting/__init__.py", line 267, in calc_percent
    a = (y-k)/(h-x)**2
UnboundLocalError: local variable 'y' referenced before assignment

```

or this seems like it has useful information regarding the missing variable

```
Logger: homeassistant.helpers.entity
First occured: March 16, 2020, 6:25:57 PM (647 occurences)
Last logged: March 16, 2020, 11:59:45 PM

Update for sensor.circadian_values fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/circadian_lighting/sensor.py", line 95, in update
    self._cl.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/circadian_lighting/__init__.py", line 305, in _update
    self.data['percent'] = self.calc_percent()
  File "/config/custom_components/circadian_lighting/__init__.py", line 267, in calc_percent
    a = (y-k)/(h-x)**2
UnboundLocalError: local variable 'y' referenced before assignment
```

oddly enough, I think it might work until the usual reboot before bed....um..scratch that ... it works after 12am? check out this graphic, shows it works most of the time, the only time it doesn't work is 6pm-12am?? and it just kinda lags out during that time until 12am when it resets and continues the cycle? that is at least what I am seeing here.

![image](https://user-images.githubusercontent.com/58420778/76826514-9fd89180-67ea-11ea-811d-e0347261dea1.png)

**Comment by claytonjn** [comment]
Those are still just the errors. I want to see what's leading up to the errors. With debug logging turned on you should see at least some of the below before an error is thrown:

```
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] now: 2020-03-17 09:14:30.665598-04:00
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] Astral location: name/region, tz=Europe/London, lat=13.74, lon=100.52
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] today_sun_times: {'sunrise': datetime.datetime(2020, 3, 16, 23, 22, 39, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'sunset': datetime.datetime(2020, 3, 17, 11, 29, 36, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'solar_noon': datetime.datetime(2020, 3, 17, 5, 26, 7, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'solar_midnight': datetime.datetime(2020, 3, 16, 17, 26, 4, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>)}
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] Astral location: name/region, tz=Europe/London, lat=13.74, lon=100.52
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] tomorrow_sun_times: {'sunrise': datetime.datetime(2020, 3, 17, 23, 21, 59, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'sunset': datetime.datetime(2020, 3, 18, 11, 29, 41, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'solar_noon': datetime.datetime(2020, 3, 18, 5, 25, 50, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'solar_midnight': datetime.datetime(2020, 3, 17, 17, 25, 47, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>)}
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] now_seconds: 1584450870.665598
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] sunrise_seconds: 1584487319.0
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] sunset_seconds: 1584444576.0
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] solar_midnight_seconds: 1584465947.0
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] solar_noon_seconds: 1584422767.0
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] h: 1584465947.0
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] k: -100
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] x: 1584444576.0
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] y: 0
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] a: 2.1895270319675172e-07
2020-03-17 09:14:30 DEBUG (SyncWorker_95) [custom_components.circadian_lighting] percentage: -50.23295724576205
```

**Comment by VarenDerpsAround** [comment]
I had to open it up in notepad++, seems like a 85Mb log file really does not get along with the front end....even after clicking "show all logs." After loading up notepad++ I found a large amount of the logs there were not showing up in hass...

I'll once again paste all instances of circadian lighting, this time from the raw file via notepad++.

I hate this though, the logs only go back to 2020-03-17 01:09:39 ... This is honestly starting to annoy the crap out of me. I just want to help, but I can't even freaking get the logs pasted right. I just spent 30 minutes control-f the log file for the errors only to find out it doesn't go back that far? WOW. Okay, once again, back to square one. I will let the shit run for another 12 hours until 6pm tonight when I will reopen the raw file, and control-f and pray I find the correct debug line...

Once again, waiting until it breaks to try and find the debug line. It only goes back to 1am, 1 hour after the error stops. .. .. I cannot believe this honestly.

**Comment by VarenDerpsAround** [comment]
Okay, back on the job. It's 10:09pm. I'll update this reply with anything I find.

**Comment by VarenDerpsAround** [comment]
Should I still be recording logs? Should I send tonight's as well? It seems now that I look at it mine is missing some of the data your example gives, could this be the issue?

regards

**Comment by claytonjn** [comment]
Sorry, I don't get a notification when an edit is made to an existing post. 

The problem is definitely that "now_seconds" (the current time in seconds since epoch) is larger than both sunrise and sunset. It _should_ always be between them. I believe this is due to timezone discrepancies as I guessed. 

Can you try beta release I just pushed on the dev branch and let me know if that fixes the issue for you?

**Comment by claytonjn** [comment]
Just updated the release so if you downloaded in the last couple hours please download again to test.

**Comment by VarenDerpsAround** [comment]
I'm not sure what changed in the repository, but both the most updated version, and the master copy via hacs result in the same error after the 6pm mark. I had to wait until 6pm to test it, but it's still throwing this error(s)/data

```
2020-03-19 18:58:24 INFO (MainThread) [homeassistant.setup] Setting up circadian_lighting
2020-03-19 18:58:24 DEBUG (SyncWorker_4) [custom_components.circadian_lighting] now: 2020-03-19 18:58:24.809609-05:00
2020-03-19 18:58:24 DEBUG (SyncWorker_4) [custom_components.circadian_lighting] Astral location: name/region, tz=Europe/London, lat=13.74, lon=100.52
2020-03-19 18:58:24 DEBUG (SyncWorker_4) [custom_components.circadian_lighting] today_sun_times: {'sunrise': datetime.datetime(2020, 3, 18, 23, 19, 58, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'sunset': datetime.datetime(2020, 3, 19, 11, 30, 53, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'solar_noon': datetime.datetime(2020, 3, 19, 5, 25, 25, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'solar_midnight': datetime.datetime(2020, 3, 18, 17, 25, 22, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>)}
2020-03-19 18:58:24 DEBUG (SyncWorker_4) [custom_components.circadian_lighting] Astral location: name/region, tz=Europe/London, lat=13.74, lon=100.52
2020-03-19 18:58:24 DEBUG (SyncWorker_4) [custom_components.circadian_lighting] tomorrow_sun_times: {'sunrise': datetime.datetime(2020, 3, 19, 23, 19, 17, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'sunset': datetime.datetime(2020, 3, 20, 11, 30, 58, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'solar_noon': datetime.datetime(2020, 3, 20, 5, 25, 7, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>), 'solar_midnight': datetime.datetime(2020, 3, 19, 17, 25, 4, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>)}
2020-03-19 18:58:24 DEBUG (SyncWorker_4) [custom_components.circadian_lighting] now_seconds: 1584662304.809609
2020-03-19 18:58:24 DEBUG (SyncWorker_4) [custom_components.circadian_lighting] sunrise_seconds: 1584659957.0
2020-03-19 18:58:24 DEBUG (SyncWorker_4) [custom_components.circadian_lighting] sunset_seconds: 1584617453.0
2020-03-19 18:58:24 DEBUG (SyncWorker_4) [custom_components.circadian_lighting] solar_midnight_seconds: 1584638704.0
2020-03-19 18:58:24 DEBUG (SyncWorker_4) [custom_components.circadian_lighting] solar_noon_seconds: 1584595525.0
```

```

2020-03-19 18:58:26 ERROR (MainThread) [homeassistant.setup] Error during setup of component circadian_lighting
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/circadian_lighting/__init__.py", line 112, in setup
    interval, transition)
  File "/config/custom_components/circadian_lighting/__init__.py", line 138, in __init__
    self.data['percent'] = self.calc_percent()
  File "/config/custom_components/circadian_lighting/__init__.py", line 267, in calc_percent
    a = (y-k)/(h-x)**2
UnboundLocalError: local variable 'y' referenced before assignment

```

Am I using the wrong version?

**Comment by claytonjn** [comment]
Yes, the beta version is 1.0.12b on the dev branch (https://github.com/claytonjn/hass-circadian_lighting/releases). If you're using HACS find Circadian Lighting under Installed and then tap the three dots menu and hit show beta. HACS should then show you 1.0.12b as an update

**Comment by VarenDerpsAround** [comment]
![image](https://user-images.githubusercontent.com/58420778/77251006-c303a680-6c19-11ea-9334-8a306d7888e9.png)
Awesome! Looks like all is functioning as intended. I'll let you close this thread, you earned it. Thanks for your help, and for being uber patient.
